version: '3.5'
services:
  loterioma_engineer:
    build: .docker/php
    container_name: loterioma_engineer
    stdin_open: true
    tty: true
    ports:
      - 5902:80
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    volumes:
      - .:/var/www/html
    networks:
      - my-proxy-net

  loterioma_engineer_db:
    image: mysql:5.7
    logging:
      driver: "none"
    command: --default-authentication-plugin=mysql_native_password --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    restart: on-failure
    environment:
      MYSQL_DATABASE: loterioma
      MYSQL_USER: loterioma
      MYSQL_PASSWORD: loterioma
      MYSQL_ROOT_PASSWORD: loterioma
    networks:
      - my-proxy-net

  loterioma_engineer_qa:
    build: .docker/phpqa
    container_name: loterioma_engineer_qa
    stdin_open: true
    tty: true
    depends_on:
      - loterioma_engineer
    environment:
      - PHPQA_HOME_DIR=/phpqa
      - PHPQA_CODE_DIR=${PHPQA_HOME_DIR}/code
      - PHPQA_LOGS_DIR=${PHPQA_HOME_DIR}/logs
      - PHPQA_TEST_DIR=${PHPQA_HOME_DIR}/code
      - PHPQA_ENGINEER_HOST=loterioma_engineer
      - PHPQA_ENGINEER_PORT=80
      - PHPQA_MACHINE_NAME=dev-local-rm
      - PHPQA_COMPONENT_NAME=engineer
    volumes:
      - ./src:/code
      - ./.docker/phpqa/results:/logs
    networks:
      - my-proxy-net

networks:
  my-proxy-net:
    external: true
    name: loterioma-net